### ISSUE TITLE
Wiki/Documentaion?

### ISSUE THREAD

**Issue by Lioncat2002** [delightedcat/TiledCS.Extensions.MonoGame#1]
Hello I noticed that even though this is a very cool project
It pretty much lacks a documentation
are there any plans to implement one?

**Comment by delightedcat** [comment]
First of all, thank you for opening an issue! You are absolutely right--The project surely lacks some documentation on how to implement the library into your MonoGame project. It was meant to be transferred from an old repository of mine, but this didn't actually happen, so that's on me.

I'm going to look into adding some proper documentation and/or "Getting Started" guide, hoping to attract more people to use this library.

Feel free to leave the issue open in the meantime, I might post an update here!

**Comment by Lioncat2002** [comment]
Thank you :) I will be waiting
Your library looks awesome so far

**Comment by delightedcat** [comment]
Thank you! Although I haven't been able to work on this library as much as I wanted, I was able to add a short section about how to install the Content Pipeline.

I'm planning on doing some changes to the build-in rendering system since it's not viable to keep maintaining it - it's simply too much of an abstract method and most people will probably want to handle their own rendering code based of some proper examples that I'll be taking care of moving forward. I'll create an issue on this!

Please let me know if this clears things up for you. I should definitely work on this library a bit more.

**Comment by delightedcat** [comment]
Closed due to inactivity. Feel free to reopen this issue if you'd like to expand the discussion.
